import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Navigation from "@/components/layout/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  void children;

  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="p-4 w-full max-w-[960px] mx-auto h-screen flex flex-col">
            <header className="flex justify-between items-center">
              <div>BOOKS</div>
              <Navigation />
            </header>
            <main className="flex-1 min-h-0 overflow-hidden mx-4 my-6">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
